# Maintenance targets for the tmpl repository.

.POSIX:
.PHONY: index

# Rebuild INDEX.md from the templates and their summary comments.
index:
	{ printf '# Index\n\nGenerated by `make index`. Do not edit by hand.\n\n| Template | Summary |\n|---|---|\n'; \
	  bin/tmpl -l | awk -F '\t' '{ printf "| `%s` | %s |\n", $$1, $$2 }'; } > INDEX.md
