# Maintenance targets for the tmpl repository.

.POSIX:
.PHONY: index check check-sh check-c check-lisp check-py check-index

PYTHON = python3

# Replace every placeholder with a word so the checkers see valid syntax.
FILL = sed 's/<+[^>]*+>/x/g'

# Rebuild INDEX.md from the templates and their summary comments.
index:
	{ printf '# Index\n\nGenerated by `make index`. Do not edit by hand.\n\n| Template | Summary |\n|---|---|\n'; \
	  bin/tmpl -l | awk -F '\t' '{ printf "| `%s` | %s |\n", $$1, $$2 }'; } > INDEX.md

check: check-sh check-c check-lisp check-py check-index

# Parse every shell template with sh -n and shellcheck.
check-sh:
	@status=0; \
	for f in $$(grep -l '<+' $$(find sh -type f) openrc.init bin/tmpl); do \
	  $(FILL) "$$f" > .check.sh; \
	  sh -n .check.sh || { echo "sh -n: $$f"; status=1; }; \
	  shellcheck -s sh -S warning .check.sh || { echo "shellcheck: $$f"; status=1; }; \
	done; rm -f .check.sh; exit $$status

# Compile every C template with the placeholders replaced by a statement.
check-c:
	@status=0; \
	for f in $$(grep -l '<+' c/*.c); do \
	  sed 's/<+[^>]*+>/;/g' "$$f" | cc -fsyntax-only -x c - || { echo "cc: $$f"; status=1; }; \
	done; exit $$status

# Read every Common Lisp template. Skip when sbcl is not installed.
check-lisp:
	@command -v sbcl >/dev/null || { echo "check-lisp: sbcl not installed, skipped"; exit 0; }; \
	status=0; \
	for f in $$(grep -l '<+' cl/*); do \
	  $(FILL) "$$f" > .check.lisp; \
	  sbcl --script tests/read-forms.lisp .check.lisp || { echo "read: $$f"; status=1; }; \
	done; rm -f .check.lisp; exit $$status

check-py:
	$(PYTHON) -m pytest -q

# INDEX.md must match the templates.
check-index: index
	git diff --exit-code -- INDEX.md
