#!/sbin/openrc-run
# OpenRC service script

command="<++>" # absolute path
command_args="<++>" # pid file, run as daemon

# command_background="yes" # if you can't run as daemon natively
# pidfile="/run/$RC_SVCNAME.pid" # if you can get one from the command/want to be able to stop it with pid signals

depend() {
	# add as required
	need <++>
	#want <++>
	#use <++>
	#provide <++>
	# will start immediately before/after something else (prevents parallelisation)
	#before <++>
	#after <++>
}

start() {
	ebegin "Starting <++>"
	# --ionice 2:7 --nicelevel 12 # example nice levels
	start-stop-daemon \
		--start \
		--name <++> \
		--exec "$command" \
		-- $command_args
	eend $?
}

stop() {
	start-stop-daemon --stop --quiet --pidfile "/run/$RC_SVCNAME.pid"
}
